services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: airbnb
      POSTGRES_DB: airbnb
    ports: 
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: simoProject@gmail.com
      PGADMIN_DEFAULT_PASSWORD: airbnb
    ports:
      - "8081:80"

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_container
    restart: always
    volumes:
      - ./project:/var/www/html
    ports:
      - "80:80"